services:
  ecommbackend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env.production
    expose:
      - 5000
    command: node dist/index.js

  ecommfrontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env.production
    expose:
      - 3000
    command: node server.js

  ecommpostgresdatabase:
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - 5432
