services:
  ecommbackend:
    container_name: ecommbackend
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - ecommnetwork
    depends_on:
      - ecommpostgresdatabase

  ecommfrontend:
    container_name: ecommfrontend
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - ecommnetwork

  ecommpostgresdatabase:
    container_name: ecommpostgresdatabase
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ecommdata:/var/lib/postgresql
    networks:
      - ecommnetwork

  ecommadminer:
    container_name: ecommadminer
    image: adminer:5.4.2
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=ecommpostgresdatabase
    networks:
      - ecommnetwork
    depends_on:
      - ecommpostgresdatabase

networks:
  ecommnetwork:

volumes:
  ecommdata:
