services:
  ecommbackend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./backend/.env.development
    volumes:
      - ./backend:/home/ecomm/backend
      - /home/ecomm/backend/node_modules
    command: pnpm run dev

  ecommfrontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env.development
    volumes:
      - ./frontend:/home/ecomm/frontend
      - /home/ecomm/frontend/node_modules
      - /home/ecomm/frontend/.next
    command: pnpm run dev

  ecommpostgresdatabase:
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  ecommadminer:
    ports:
      - 8080:8080
